### ISSUE TITLE
Error in controlStripPlot()

### ISSUE THREAD

**Issue by wudustan** [kasperdanielhansen/minfi#80] opened 2016-09-28 14:47 UTC
In the function controlStripPlot() (line 45 of qc.R) 

`if (!is.null(sampNames)) colnames(ctlWide) <- sampNames`

ctlWide is a numeric and can not be assigned colnames(). I assume this was changed from names() which works fine. I have tried the most recent (not devel) version of minfi and the error still persists. 

The error returns:

`Error in colnames<-(*tmp*, value = c("687L", "686L",  : 
attempt to set 'colnames' on an object with less than two dimensions`

Further down in the same function (line 50, qc.R) it also tries to do this for the green channel.

I also have had issues with preprocessFunnorm() but I have yet to trace the issue. It may be related since it was cropping up in the same analysis.

Cheers

**Comment by Jfortin1** [comment] 2016-10-31 14:11
I cannot reproduce the error. Is it still causing you problem?

**Comment by wudustan** [comment] 2017-03-30 14:01
Hi,

Yes, I just ran this today and I still get the same issue.

**Comment by kasperdanielhansen** [comment] 2017-04-05 19:19
We have `drop=FALSE` in the devel version on GitHub.  That should fix the problem. Not clear when that was added, but it is a while ago.  I'm closing the report since I assume it is fixed in devel.

**Closed by kasperdanielhansen** 2017-04-05 19:19 UTC
