### ISSUE TITLE
getMeth(MethylSet) => Error

### ISSUE THREAD

**Issue by NizarTouleimat** [kasperdanielhansen/minfi#93] opened 2017-01-25 14:38 UTC
Dear Kasper,

I am working on methylation EPIC array data.
I was using the functions getMeth and getUnmeth to respectively extract 'methylated' and 'unmethylated' signals from a MethylSet object.
However, I think that until the laste release of minfi, when I use this function getMeth(MethylSet) I get this error message :
Error: is(BSseq, "BSseq") is not TRUE

This error does'nt appear when using getUnmeth(MethylSet).

Is there any conflict between functions ? Should I use another function ?

Many thanks for your help !

Best regards,

Nizar Touleimat

**Comment by kasperdanielhansen** [comment] 2017-01-25 14:48
This is because you also have bsseq loaded.  Both bsseq and minfi have a
getMeth() function, but they are different.  You can always specify by
minfi::getMeth() and bsseq::getMeth().

But I should really think about fixing this, since I have written both of
the packages and it is not unreasonable to have them both loaded at the
same time.

Best,
Kasper

**Comment by NizarTouleimat** [comment] 2017-01-30 10:15
Thank you for your quick reply.
It works now with minfi::getMeth().

Best,
Nizar

**Comment by kasperdanielhansen** [comment] 2017-04-07 18:37
Duplicate of #39, so closing this one.

**Closed by kasperdanielhansen** 2017-04-07 18:37 UTC
