### ISSUE TITLE
bad dmap causing problems

### ISSUE THREAD

**Issue by will-NYGC** [kasperdanielhansen/minfi#67] opened 2016-06-30 21:50 UTC
Hi Kasper, 

Just thought we'd give you a heads up. We ran a few EPIC arrays from different batches and turns out some had old dmap files. As a result of this, when reading the G.idats and R.idats objects with readIDAT from "illuminaio" in the read.metharray() function,  the G.idats[[]]$Quants and R.idats[[]]$Quants matrices do not have the same ordering. The subsequent do.call(cbind) operations then create GreenMean(SD|NBeads) and RedMean(SD|NBeads) objects that can have sample intensities out of order in some of the columns becauase the rowname probe addresses of the first sample will be forced onto the rest of the cbind samples even though they have a matrix with a different row ordering because the older dmap file--many of samples will then have shuffled probe intensity values. 

Genome Studio correctly handles this problem so we completely missed it in the QC in that software. We only found it later when our collaborators ran minfi and it appeared as if all the samples with with old dmap files had high background and extremely poor detP's--this was only because all of the negative control probes were shuffled and not assigned the proper address. 

Let me know if this doesn't make sense. This problem should be rare since i believe illumina has fixed the dmap problem but just in case it might be safe to just order those G.idats[[]]$Quants and R.idats[[]]$Quants by rownames before cbind'ing.

best,
will

**Comment by kasperdanielhansen** [comment] 2016-07-01 01:09
Thanks for the report. Illumina just told me about "some bioinformatician" with this problem. Guess it was you.

This is already fixed in the devel branch of minfi; certainly version 1.19.6 or greater has the following capability: It detects if all the IDAT files have the same probes, and if not, allows you to force them into the same structure, implicitly dropping probes which are not present on all arrays.  

Based on your report I will backport this fix to the stable release; look out for version 1.18.3 appearing in a few days.

**Comment by letaylor** [comment] 2016-08-18 09:31
Hi Kasper,

In the developmental minfi on Bioconductor (1.19.10) this still seems to be a bug. When using the current release (1.18.6) everything works fine. 

Best, 
--Leland

**Comment by kasperdanielhansen** [comment] 2016-08-18 18:46
That is correct and embarrassingly.  Specifically I write above that the issue is fixed in minfi version 1.19.6 or greater.  This is not true: the bug is still present in mini 1.19.10.  It is however fixed in version 1.19.12 which was committed a long time ago (and available through `install_github()`) but is not building because some data packages has not been updated.  I will try to fix this asap.

**Comment by will-NYGC** [comment] 2016-11-07 18:49
Hi Kasper, i was running 1.19.2 which tested ok and bug was fixed but weirdly it's now reappeared. So, tried updating to 1.21 + Biobase v.2.35.0 but keep getting the assayDataElement error (validate=TRUE isn't a parameter). I've tried stepping down to 1.20 and Biobase v2.34.0 and v2.32.0 and various permutations without lunch. Do you know a surefire combination to resolve the bug again?

**Comment by kasperdanielhansen** [comment] 2016-11-07 19:01
Well, you should watch out with mixing different versions of the packages.
To check this, you can run `biocValid()` to check the validity of your
installation.  The validate=TRUE issue should not be an issue if you match
packages in the right way.

I am (somewhat) convinced that the dmap issue should be solved, so I would
like to hear back with (1) two files that fail and (2) output from
biocVaid() showing that your installation is "legit".

Best,
Kasper

**Comment by will-NYGC** [comment] 2016-11-11 18:59
Thanks Kasper,

Double checked versions and turns out doesn't look like a dmap problem after all--backgrounds are probably extracted. Rather, issue was I was normalizing with funNorm and one of the arrays failed. When I exclude and rerun, everything seems better. Thanks for help.

will

**Closed** 2016-11-11 19:03 UTC
